services:
  apache:
    build:
      context: .
      dockerfile: config/apache/Dockerfile
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      - apache_data:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
    networks:
      - backend
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/php-app:/var/www/html

  php-fpm:
    image: ukf/vk-2026-be:latest
    build:
      context: .
      dockerfile: config/php-fpm/Dockerfile
    networks:
      - backend
    volumes:
      - ./src/php-app:/var/www/html

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql


networks:
  backend:
    driver: bridge

volumes:
  apache_data:
  mysql_data: